# Generated by Django 4.2.7 on 2025-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("suite", "Suite"),
                            ("deluxe", "Deluxe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pricePerNight",
                    models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RON", "RON"), ("EUR", "EUR")],
                        default="RON",
                        max_length=10,
                    ),
                ),
                ("maxOccupancy", models.IntegerField(default=1)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
    ]
